blank_issues_enabled: true
contact_links:
  - name: 🪶 Feishu community group
    url: https://applink.feishu.cn/client/chat/chatter/add_by_link?link_token=0far82db-f790-412e-9217-58ae67df4313
    about: Chat with the community and ask questions in our Feishu group
